### ISSUE TITLE
"Anonymize your users" doesn't work in search dropdown

### ISSUE THREAD

**Issue by gxjansen** [Linen-dev/linen.dev#1027]
I've enabled "Anonymize your users", but when I search for something, the search result dropdown shows the user names. (It does work on the results page itself, it's the dropdown that shows the names)
<img width="392" alt="Screenshot at Mar 01 23-00-31" src="https://user-images.githubusercontent.com/487722/222274776-8b1761ca-d956-4141-b529-b49037a609e0.png">

**Comment by sandrodesouza** [comment]
[fix: anonymous authors and mentioning on search](https://github.com/Linen-dev/linen.dev/commit/997aff6b06fc0f90da619bf60816bd793568c81d)
