### ISSUE TITLE
The setting to "Add channels to your workspace" behaves very oddly 

### ISSUE THREAD

**Issue by villuminati** [Linen-dev/linen.dev#1065]
I was just testing out creating community when I ran into this bug. 

I tried to add channel to the new workspace using the setting "Add channels to your workspace", it wouldn't let me add the channel.

![image](https://user-images.githubusercontent.com/14012422/224579849-aa563ef5-5bdb-4d69-89f9-f111761447c1.png)

**Comment by villuminati** [comment]
I hope this is the right place to file bugs. Please let me know in case I was wrong.

**Comment by emilos** [comment]
Thanks @villuminati! I've fixed it here https://github.com/Linen-dev/linen.dev/pull/1074. Please let us know if you find any other problems.

**Comment by villuminati** [comment]
Thanks for taking care of this so fast @emilos
