### ISSUE TITLE
Click-and-dragging to select text automatically deselects text (preventing the user from copying text)

### ISSUE THREAD

**Issue by Nezteb** [Linen-dev/linen.dev#1087]
macOS Ventura 13.2.1

This happens in Brave Browser as well as Safari (both of which are up-to-date).

Click-and-dragging to select text doesn't work in the main chat window, but _does_ work in threads for some reason.

Bug demo:

https://user-images.githubusercontent.com/3588798/226727814-a4e2b0ae-8348-4fd2-b6c7-969370272538.mov

**Comment by emilos** [comment]
https://github.com/Linen-dev/linen.dev/pull/1088/commits/5646c330c9fa1a5ec05bfed09d95905380f1af48

@Nezteb thanks!

**Comment by Nezteb** [comment]
![fastest-open-source-fix](https://user-images.githubusercontent.com/3588798/226965021-7d3f7c62-e7f1-4cc1-986b-b7d8c7f84de4.gif)
