### ISSUE TITLE
Official website "Premium features" text description seems truncated

### ISSUE THREAD

**Issue by cpcdoy** [Linen-dev/linen.dev#1144]
Hi,

A small detail I noticed on [linen.dev](https://www.linen.dev/) but the following text is truncated and ends at `not`:

```
Custom branding

Get branded colors and logos of your community or company. Your community should feel like yours and not
```

You probably meant `not like someone else's.` or something else.

Hope this helps!

**Comment by cheeseblubber** [comment]
Thanks! We actually ended up redesigned the website this week. Let us know if you find any new issues
