### ISSUE TITLE
Desktop: Fix windows build

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#1211]

**Comment by emilos** [comment]
`packages/ui` windows build has been fixed, I can also run spa client locally on a windows machine correctly and I don't get any other js issues anymore.

cc @sandrodesouza if there's anything else to be done here. I'll try to run tauri on my windows machine in the meantime.

**Comment by sandrodesouza** [comment]
@emilos can you check these logs on the windows build https://github.com/Linen-dev/tauri/actions/runs/5148624290
