### ISSUE TITLE
StatusCode:: 401, Message:: Unauthorized

### ISSUE THREAD

**Issue by dillfrescott** [Linen-dev/linen.dev#1245]
This error has been appearing, preventing me from even seeing a login screen on my newly self hosted linen instance

**Comment by dillfrescott** [comment]
I am not seeing any documentation on how to create the first admin user or anything... :(

**Comment by cheeseblubber** [comment]
You don't need an admin user. You can just create a community. To make someone a premium account you'd have to go in to the db and change the account to premium. Self hosting isn't in a great spot right now since we are missing a lot of the admin features and documentation for self hosting.

**Comment by dillfrescott** [comment]
Ohhh okay. Thank you for the info!

**Comment by mcnaveen** [comment]
Hi, @cheeseblubber Any ETA on the self-hosting documentation?

**Comment by emilos** [comment]
@mcnaveen it's very low on the priority list (please have a look at the roadmap). Contributions are welcome though if you want to play around and document the process a bit

**Comment by mcnaveen** [comment]
Cool. Will have a look.
Thanks. :)
