### ISSUE TITLE
Deep link to a thread in the general page

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#1247]
We should deep link to a page with chat available, the thread opened on the right side and the center page being selected. It should also work for an older thread that isn't loaded yet.

**Comment by sandrodesouza** [comment]
hey emil, it will work if the thread is in the latest page or it was loaded, at least for the SPA https://github.com/Linen-dev/linen.dev/commit/5e44a7c3368ccdd8ed19cb5df203b39a0db3c6ef
