### ISSUE TITLE
In an existing channel I should be able to add members

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#1253]
You should be able to add someone in the invite section in the configuration button next to the channel

**Comment by emilos** [comment]
@cheeseblubber I think we have a members modal for private channels already. Is this dedicated for private channels only or for all channels?

**Comment by cheeseblubber** [comment]
This should be for all channels. I think this is a blocker https://github.com/Linen-dev/linen.dev/issues/1252
