### ISSUE TITLE
500 Error on startup

### ISSUE THREAD

**Issue by sameer-coder** [Linen-dev/linen.dev#1298]
Hey team,

Trying out the latest release on windows 10, I ran across a 500 error
![image](https://github.com/Linen-dev/linen.dev/assets/2347454/179456c7-dc05-4e19-895d-85adb6158338)

**Comment by cheeseblubber** [comment]
We just shipped a fix https://github.com/Linen-dev/linen.dev/commit/0bb8cac8eeaefe03fe67e857ace2dcd0f9542fb7 will push a release for windows soon

**Comment by cheeseblubber** [comment]
Fixed it if you download the latest build from https://github.com/Linen-dev/desktop-client/releases/tag/v0.0.19 it should have the fix
