### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by lapaz17** [Linen-dev/linen.dev#1308]
?

**Comment by cheeseblubber** [comment]
@lapaz17 we're going to do some planning tomorrow I can create some issues that is beginner friendly

**Comment by HN026** [comment]
Sure, please do it ASAP

**Comment by vahabrajabi** [comment]
@lapaz17 Perfect!

**Comment by cheeseblubber** [comment]
We've added a few issues labeled with "help wanted" https://github.com/Linen-dev/linen.dev/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22 

We'll add more later on. 

I've also added how-to-contribute section in the readme 
https://github.com/Linen-dev/linen.dev/tree/main#how-to-contribute

I also created this issue for mobile testing:
https://github.com/Linen-dev/linen.dev/issues/1311

We plan on building a Mobile app for Linen. We want to make sure our app is mobile friendly first. We think there are quite a bit of rough edges there

Finally I would love to chat with you all individually we're trying to get as much high quality user interviews as possible.
