### ISSUE TITLE
Email validation is missing before calling the invite API

### ISSUE THREAD

**Issue by shubhamkhunt04** [Linen-dev/linen.dev#1315]
Issue description:- If we invite a member on the settings/members screen, we should first validate that the email input field is valid or not, before calling the invite API.

Reference video:- 

![emailbug](https://github.com/Linen-dev/linen.dev/assets/55044317/d5b057c1-cbf1-4673-b300-8c6561b9bbd4)

**Comment by cheeseblubber** [comment]
Agreed. We can start with a simple client side validation first

**Comment by shubhamkhunt04** [comment]
@cheeseblubber Could you please assign this issue to me? I would be happy to take care of it and work on a solution.

**Comment by shubhamkhunt04** [comment]
@emilos Could you please assign this issue to me?
