### ISSUE TITLE
Not able to run DB migration script

### ISSUE THREAD

**Issue by shubhamkhunt04** [Linen-dev/linen.dev#1317]
**Node version**
v16.14.2

**Docker setup status:-**
<img width="1248" alt="Screenshot 2023-06-25 at 10 15 34 AM" src="https://github.com/Linen-dev/linen.dev/assets/55044317/defa8952-58d9-4a0d-960b-433b89c89228">

**Steps to reproduce the bug:-** 
To get started, I followed the steps in https://github.com/Linen-dev/linen.dev/blob/main/docs/getting-started.md 

The `yarn migrate:db` command throws the following error

<img width="577" alt="Screenshot 2023-06-25 at 10 10 26 AM" src="https://github.com/Linen-dev/linen.dev/assets/55044317/9327b068-3721-4f40-beb2-3458a46dc894">

**Comment by sandrodesouza** [comment]
hi @shubhamkhunt04 is probably related to the default value of NEXTAUTH_SECRET on the .env, please be sure to create a secret and replace the default value

**Comment by sandrodesouza** [comment]
Hey @shubhamkhunt04 I'm going to close this, let me know if you have issues.

**Comment by shubhamkhunt04** [comment]
Sure, it's working now, Thank you :)

**Comment by shubhamkhunt04** [comment]
@sandrodesouza Can you help me to bypass the email verification because I'm not able to signup in my local setup?

**Comment by shubhamkhunt04** [comment]
Yes, But in my local there is no any SMTP server to receive a mail, i tried smtp4dev with docker image file but it is not working

**Comment by sandrodesouza** [comment]
you don't need that for local dev, try to signup on http://localhost:3000/signup?mode=creds

**Comment by shubhamkhunt04** [comment]
@sandrodesouza Ohh Yeah It is working, Thank you :)

**Comment by sandrodesouza** [comment]
nice

**Comment by shubhamkhunt04** [comment]
@sandrodesouza could we mention this in the getting-started readme file?

**Comment by sandrodesouza** [comment]
is here but isn't that clear https://github.com/Linen-dev/linen.dev/blob/main/docs/getting-started.md?plain=1#L61, be free to update the docs to be more understandable :)
