### ISSUE TITLE
Fix README logo in the dark mode

### ISSUE THREAD

**Issue by emilos** [Linen-dev/linen.dev#1332]

**Comment by dexterbrian** [comment]
Hello. I'd like to work on this. Could there be any information that I need before I proceed?

**Comment by dexterbrian** [comment]
Hello. Please assign this to me.

**Comment by dexterbrian** [comment]
Hello @emilos I have opened a pull request.

**Comment by emilos** [comment]
thanks @dexterbrian, looks good!

**Comment by dexterbrian** [comment]
After I saw that my pull request was accepted, I went to the repo's README to check it out. I was shocked to see two Linen logos appearing, both the white and black one. After tinkering with the code a bit more, I think I've figured it out. So I would like to submit another pull request from the same branch for this issue. I hope that's okay @emilos.
