### ISSUE TITLE
When uploading the profile(avatar) picture, users should not be able to select PDF

### ISSUE THREAD

**Issue by shubhamkhunt04** [Linen-dev/linen.dev#1334]
The current situation is that when we upload user profile pictures, there is no validation, so any file format can be used

Expected output:-
User should only select .jpg or .png or .gif file

**Comment by shubhamkhunt04** [comment]
@emilos could you please assign this to me?

**Comment by emilos** [comment]
@shubhamkhunt04 Thanks!
