### ISSUE TITLE
Replace the landing page with a feed

### ISSUE THREAD

**Issue by emilos** [Linen-dev/linen.dev#1336]

**Comment by cheeseblubber** [comment]
Stages:
1. Readonly feed of interesting content
2. Click up vote and create an account
3. Can they create a post on landing page

**Comment by cheeseblubber** [comment]
Add which community the thread is coming from.

**Comment by cheeseblubber** [comment]
1. Add back dates - time ago format shorter without that much precision. 
2. Mobile improvements - One-line description, navigation, show link to old landing page 
3. Truncation of long posts
4. Nice to have: Can they create a post on landing page

**Comment by emilos** [comment]
@cheeseblubber can you please see the current version and decide whether it's ready for the switch?
