### ISSUE TITLE
Add instructions for Discord onboarding flow

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#1388]
Some discord communities aren't syncing data because they don't give the bot proper permissioning which doesn't end up syncing.

At the end of clicking Discord sync we should give a checkbox or task to make sure you give the bot the proper permissions. Maybe even add some documentation as well

https://www.linen.dev/s/burning-sea

**Comment by MadeByDouglas** [comment]
This could still be elaborated upon, I saw the pop up, but what permissions do I need to give it? How do I know if it has what it needs? Should it be given administrator privileges and just be done with it?

**Comment by sandrodesouza** [comment]
We recommend giving it the same role that a new member would have. Generally a role with access to public channels.

**Comment by MadeByDouglas** [comment]
OK, so basically read and write to public channels? Thanks.
