### ISSUE TITLE
Sort channels alphabetically

### ISSUE THREAD

**Issue by martinbonnin** [Linen-dev/linen.dev#1391]
Hi 👋 

When going to https://slack-chats.kotlinlang.org/, the channels in the left side bar seem to be sorted arbitrarily:

![Screenshot 2023-07-19 at 15 35 27](https://github.com/Linen-dev/linen.dev/assets/3974977/fbc01c1d-6639-4be6-9275-630af3884dbb)

This makes it quite hard to find a specific channel. Could the channels be sorted alphabetically?

Context: [linen link to the KotlinLang slack discussion](https://slack-chats.kotlinlang.org/t/13226465/i-love-that-i-can-point-anyone-to-this-slack-using-http-line#b1826f15-731d-47d6-9d75-e3808b697769)

**Comment by cheeseblubber** [comment]
We actually let users custom sort the channels. We can give someone from the Kotlin team access to organize it.

**Comment by martinbonnin** [comment]
Thanks for the context 👍
