### ISSUE TITLE
Making feed search engine friendly

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#1418]
Spike on a day on how to make it Search engine friendly

**Comment by emilos** [comment]
I've submitted the URL for manual indexing in the google search console. It wasn't indexed yet.

Next steps:

We could make it easier for search engines to discover new content on our platform by:
- adding the homepage to the sitemap
- adding RSS/Atom feed to make it easier for crawlers to discover new content https://developers.google.com/search/blog/2009/10/using-rssatom-feeds-to-discover-new
