### ISSUE TITLE
Mobile friendly feed view

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#532]
Right now you can't get in to mobile view for the feed. We should improve the UX around feed

**Comment by cheeseblubber** [comment]
<img width="509" alt="Screen Shot 2022-10-12 at 10 33 17 AM" src="https://user-images.githubusercontent.com/4218509/195376910-44ef6eb7-9aef-4a2a-a4e9-76e32087a730.png">

**Comment by emilos** [comment]
https://github.com/Linen-dev/linen.dev/pull/555
