### ISSUE TITLE
Can't post to your community 

### ISSUE THREAD

**Issue by glasgowm148** [Linen-dev/linen.dev#573]
No option to add a comment here when logged in 

https://www.linen.dev/s/linen/c/intros

Can see the add comment box on my own community.

**Comment by emilos** [comment]
Hey @glasgowm148! Thanks for the bug report. I've merged a fix here https://github.com/Linen-dev/linen.dev/pull/575.

You should see `Join the conversation` or `Join Linen` button in the top right corner.

We're still trying to figure out the user experience for the joining process so please let us know if you encounter other issues.

**Comment by glasgowm148** [comment]
Ah I see thanks, I had ignored that as I thought it'd take me to another chat platform.

**Comment by cheeseblubber** [comment]
Yeah this is a bug. We had this ability early this week.
