### ISSUE TITLE
Getting started is confusing

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#577]
See discussion here:
https://www.linen.dev/s/linen/t/3610108/topic

Right now session and multi tenant management is not great

**Comment by glasgowm148** [comment]
Few suggestions

- Have the `Settings` page accessible when you click on your avatar top-right. When you first sign into your community, it's not clear how to set it up the connection to Discord
- Have the linen chat available on the homepage inplace (or in addition to) the demo
- More descriptive text around the connection to Discord; once it says 'Done' - do you need to re-connect for it to pull in new ones? Maybe list common errors here (make sure the bot is verified)
