### ISSUE TITLE
Investigate "Clickable elements too close together" on mobile view

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#581]
We're seeing some issues with clickable elements 
![Screen Shot 2022-10-21 at 3 26 54 PM](https://user-images.githubusercontent.com/4218509/197274393-75c7abc3-03a2-4560-a942-eb61370c898d.png)

**Comment by cheeseblubber** [comment]
Kotlin community is seeing some of this issue as well

**Comment by emilos** [comment]
@cheeseblubber I made various mobile improvements / fixes here https://github.com/Linen-dev/linen.dev/pull/607. It's hard to validate if they were good enough, so we should most likely revisit this when pages are reindexed.

**Comment by SebastianAigner** [comment]
![686F2128-55D7-474F-9EFC-3050FFEFEA67](https://user-images.githubusercontent.com/2178959/200519112-9273e418-8268-446e-9a16-0dc4c0b6035b.png)

**Comment by emilos** [comment]
Hey @SebastianAigner, I've made few additional fixes, https://github.com/Linen-dev/linen.dev/commit/5dc4e3f826fbbff040fc7e252003ca7648aa9f11 and https://github.com/Linen-dev/linen.dev/commit/10aede6c546b466af84ac46363ac11218aeb2925. Biggest issue that I found is that we've been incorrectly blocking css/js files, which ended up in a broken googlebot view (looked fine in standard dev and/or mobile view). I've rerun the validation again in google search and the validation is pending right now.

<img width="1153" alt="Screenshot 2022-11-09 at 13 34 56" src="https://user-images.githubusercontent.com/2088208/200832076-e2067607-80bb-4306-a5fb-494b460334ef.png">

If you notice anything else please let me know.

**Comment by emilos** [comment]
It got much better after recent fixes, but I had to run the validation again due to cached pages. Going to check it again next week.
