### ISSUE TITLE
404 on search results

### ISSUE THREAD

**Issue by glasgowm148** [Linen-dev/linen.dev#584]
The first result for

shows
![Screenshot 2022-10-22 at 15 10 20](https://user-images.githubusercontent.com/19927264/197343641-82baee5e-0ef9-4124-bb16-8c4f96aaf591.png)

but clicking it takes me to a broken page. Second search result works fine. 

https://www.linen.dev/d/ergo/t/3653987/Is-the-ordering-of-input-in-this-transaction-correct-https-e

Notably the first result doesn't show it as belonging to any channel.

**Comment by glasgowm148** [comment]
Ah, appears this is from an internal chat I had perhaps enabled and then disabled; so some sort of cache still in the search.

**Comment by emilos** [comment]
cc @sandrodesouza , this might be related to sync upsert
