### ISSUE TITLE
Discord Forum Channel

### ISSUE THREAD

**Issue by daprieu** [Linen-dev/linen.dev#661]
Currently, Linen provides support for only text Channels. 
We recently moved some of our Discord channels from Text to Forum, and I cannot use these with Linen.

Linen, so far, is an incredible tool. Thank you!

**Comment by erlend-sh** [comment]
I’m evaluating Linen on behalf of @tauri-apps and we’ve begun using Discord’s forum channels extensively. These forum topics are actually the primary type of content we’d like to make SEO-friendly, so we’re very interested in your plans to support them.

**Comment by erlend-sh** [comment]
Some prior art by @domitriusclark:
https://github.com/domitriusclark/discord-forum-to-website

**Comment by sandrodesouza** [comment]
[feat(sync): add support for discord forum channels](https://github.com/Linen-dev/linen.dev/commit/808d1b963d5ff9d59518e5c8d8b9cacb6b0e0029)
