### ISSUE TITLE
Support custom names for Slack communities

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#685]
Some communities don't want to use their slack community name and wants to choose their own custom one. We are configuring it manually for apache-druid for now but if they sync it would change to their old workspace

**Comment by sandrodesouza** [comment]
owner must create the community path before start the integration + [fix(web): avoid community path overwrite](https://github.com/Linen-dev/linen.dev/commit/48decd5d790c89ee85c7eca3272d1a780fa3c295)
