### ISSUE TITLE
Create a drag a drop icon instead of dragging the entire card. This will let people highlight and select the text.

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#733]
We should use 6 dots under the thread. See https://uxdesign.cc/drag-and-drop-for-design-systems-8d40502eb26d for reference.

For individual messages we could either add more spacing on the left side or on hover on date changes it to drag and drop. Not sure the best UX for individual messages

**Comment by emilos** [comment]
I've added 6 dots inside of actions, as we've discussed, for both threads and messages. That should make the experience more consistent for our users.
