### ISSUE TITLE
Email notifications for unread messages

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#735]
**Email notifications**

1. (New community messages) When you leave Linen you should get an email of new messages in the community on a weekly basis of new messages
2. (Mentions)When you leave Linen and get a mention you should get an email notification if you haven’t seen the message after 15 minutes (default)
3. (Participating Threads)When you leave Linen and someone sends a message within Linen you should get a notification after 30 minutes (default)
4. You should be able to set notifications preferences on unread messages
    1. New community messages
    2. Mentions
    3. Participating threads

**Comment by cheeseblubber** [comment]
We can break this issue out in to more tickets

**Comment by sandrodesouza** [comment]
# notification

any trigger will execute all actions previously validated with at least one condition been true

## triggers

- new thread event
- new message event

## conditions

- user is mentioned
- user is subscribed to the thread
- user is subscribed to the channel

## actions

- a new notification item will be created with unread status
- a new queue job will be created with runAt specified by type

## api

- an endpoint to get all unread notifications for a specific user
- an endpoint to mark a specific (or many) notification as read (delete it)

## queue

- the task will send an email to the user if the notification status still unread

## avoid dup notification

Task-identifier will be used to avoid duplication.
When adding a new job to our queue, a task-identifier will be defined by the notification type.

Mentions: `mention-${authId}-${threadId}`
Threads: `thread-${authId}-${threadId}`
Channels: `channel-${authId}-${channelId}`

## email template

- TBD

## schedule time by type

- mentioned: 15m
- thread: 30m
- channel: 1w

## model

- id auto-generated
- authId
- communityId
- notificationType (bang-mention, mention, thread, channel)
- channelId
- threadId
- messageId
- authorId
- createdAt
- updatedAt

**Comment by sandrodesouza** [comment]
@cheeseblubber what you think
