### ISSUE TITLE
Add options to enable app message being synced

### ISSUE THREAD

**Issue by wey-gu** [Linen-dev/linen.dev#761]
_Originally posted by @wey-gu in https://github.com/Linen-dev/linen.dev/issues/553#issuecomment-1350639608_

- linen URL for the channel: https://community-chat.nebula-graph.io/c/wechat-sync-venus
- messages synced with [chatroom-syncer](https://github.com/wey-gu/chatroom-syncer)
  
<img width="961" alt="Screenshot 2022-12-15 at 17 21 48" src="https://user-images.githubusercontent.com/1651790/207821886-3d91ce9b-7cbd-493b-b1c1-c3876b749401.png">

cc @cheeseblubber

**Comment by cheeseblubber** [comment]
@wey-gu we looked in to it Friday @sandrodesouza will give you the option of displaying bot messages this week. We'll prioritize syncing and an API endpoint sometime in the next two weeks

**Comment by wey-gu** [comment]
Amazing! Thanks so much!

The options to enable app msg being synced will be terrific!

When the api is ready, I'll add linen native sink for my chatroom sync project, too!

**Comment by cheeseblubber** [comment]
We're gonna use https://github.com/Linen-dev/linen.dev/issues/614 for discussion area for the developer apis. Can you add some comments on the ones you need.

**Comment by sandrodesouza** [comment]
Hey @wey-gu, We have enabled bot messages on our event-API handler for slack messages, which means that messages from your bot will be shown on Linen from now on. There will be a little difference between slack and linen is that all messages will have the same username (the bot name) since it comes from the same bot, we don’t support yet custom usernames for specific messages.

**Comment by wey-gu** [comment]
> Hey @wey-gu, We have enabled bot messages on our event-API handler for slack messages, which means that messages from your bot will be shown on Linen from now on. There will be a little difference between slack and linen is that all messages will have the same username (the bot name) since it comes from the same bot, we don’t support yet custom usernames for specific messages. 

thanks so much @sandrodesouza for your fast implementation in holiday season!

It's already more than perfect for me!
