### ISSUE TITLE
Question: Upload slack files doesn't work

### ISSUE THREAD

**Issue by juzhiyuan** [Linen-dev/linen.dev#764]
Hi,

1. I use SlackDump tools to export the whole workspace, it contains all messages in JSON, including Chat Messages, users.json, channels.json, ...

2. I upload the zip file to Linen
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/2106987/207990787-dd8c4106-55c9-46db-aca4-41f7a9fe8e5e.png">

3. Nothing happened after a long time

**Comment by juzhiyuan** [comment]
I just checked the source codes, it says that:

After sync, an email will be sent to notify status, but I haven't received it yet, so maybe something go wrong?

**Comment by juzhiyuan** [comment]
https://github.com/Linen-dev/linen.dev/blob/main/docs/monorepo.md

I try to run this project to debug this issue, but it's hard for beginners 🤣 

1. There are many markdown files under the `/doc` folder. I have no correct idea, and I must try each of them.
2. I try to use `docker-compose` to setup database, and try to run the next.js project, but it mentions some modules are missing 🤔 (even though I have installed all necessary dependencies)

I haven't run the project successfully so far.

**Comment by cheeseblubber** [comment]
Hey @juzhiyuan we'll take a look at the sync issue. Probably something on our end.

@sandrodesouza can you investigate the sync. 

Also for the setup you probably don't need the docker-compose. We just changed our set up because we wanted to build a desktop client and haven't updated the docs. We'll update them today!

**Comment by sandrodesouza** [comment]
Hey @juzhiyuan, I saw the zip you upload, it have a different structure to what we are expecting to have. Can you export it from Slack directly and try again? See instructions on how to export it [here](https://slack.com/help/articles/201658943-Export-your-workspace-data)

**Comment by juzhiyuan** [comment]
Thanks! Will give a try

**Comment by juzhiyuan** [comment]
Hi @sandrodesouza,

I created one Slack workspace (let's call it **WorkspaceA**) and sent some messages. After that, I log in to the dashboard and export all messages. The zip file's structure is like this:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/2106987/209608869-236751ba-f917-498d-872d-5c6e4746e4cf.png">

```json title="[channelName]/[date].json"
[
    {
        "type": "message",
        "subtype": "channel_join",
        "ts": "1648085524.129309",
        "user": "U0385EX4N6M",
        "text": "<@U0385EX4N6M> has joined the channel"
    },
    {
        "client_msg_id": "d5b5d893-270b-42aa-ad9a-0e7e1f8ea170",
        "type": "message",
        "text": "IDEA-1",
        "user": "U0385EX4N6M",
        "ts": "1648085547.139899",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "1Mbu",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "IDEA-1"
                            }
                        ]
                    }
                ]
            }
        ],
        "team": "T037V70SNRJ",
        "user_team": "T037V70SNRJ",
        "source_team": "T037V70SNRJ",
        "user_profile": {
            "avatar_hash": "g1060f8016a2",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/1060f8016a2e1bf2a4c272b481de6ee3.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0005-72.png",
            "first_name": "juzhiyuan",
            "real_name": "juzhiyuan",
            "display_name": "",
            "team": "T037V70SNRJ",
            "name": "juzhiyuan",
            "is_restricted": false,
            "is_ultra_restricted": false
        }
    }
]
```

As for another workspace (let's call it **WorkspaceB**, **this is the workspace I want to import to Linen**), I don't have permission to download those messages, so I used the tool **slackdump** to download each message. The zip file's structure is like this:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/2106987/209609095-1fb75969-4da8-448b-9733-69f93c4cf7db.png">

```json title="[channelName]/[date].json"
[
  {
    "type": "message",
    "user": "U016EPMFPK5",
    "text": "\u003c@U016EPMFPK5\u003e has joined the channel",
    "ts": "1596529218.000200",
    "subtype": "channel_join",
    "replace_original": false,
    "delete_original": false,
    "metadata": {
      "event_type": "",
      "event_payload": null
    },
    "blocks": null,
    "user_team": "",
    "source_team": "",
    "user_profile": {
      "avatar_hash": "4ee27e4e6a0c",
      "image_72": "https://avatars.slack-edge.com/2020-07-02/1203854651735_4ee27e4e6a0c8547e947_72.jpg",
      "first_name": "",
      "real_name": "Yudhi Karunia Surtan",
      "display_name": "Yudhi Karunia Surtan",
      "team": "T4S1WH2J3",
      "name": "yudhiks",
      "is_restricted": false,
      "is_ultra_restricted": false
    },
    "reply_users_count": 0,
    "reply_users": null
  }]
```

Then I compared WorkspaceA and WorkspaceB's content. **They indeed have some differences, but they are nearly the same**, because most fields exist 🤔 

Can you please check what fields I'm missing in WorkspaceB?

**Comment by sandrodesouza** [comment]
Hey @juzhiyuan, this structure seems to be fine. The problem with your first attempt was that it was missing the channels and users files. The zip file must have the channels.json on the root, and for each channel described there, a folder with the channel name must exist in the zip file.

**Comment by juzhiyuan** [comment]
Hi @sandrodesouza, thanks for your reply! But the same case still happened 🤔 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2106987/209750633-76e8afa5-87e3-4ec1-a428-8d0885f01f5b.png">

After importing, nothing happened in the channel. Here is the zip file, can you help import it to https://www.linen.dev/s/apisix/c/apisix? Thanks!

[apisix-channel.zip](https://github.com/Linen-dev/linen.dev/files/10311833/apisix-channel.zip)


By the way, if the system can let users know what error happened, that would be great!

**Comment by sandrodesouza** [comment]
Hi @juzhiyuan, the issue with the file is that the content of the zip was inside a folder "apisix-channel", we expected to have the channels.json on the root folder after unzip it. I did recreate the zip file and upload it to your community. It is available now. Lets me know any other issue/question.

**Comment by juzhiyuan** [comment]
Wow @sandrodesouza, it's much clearer now! Thanks for your help. It's now visible at https://www.linen.dev/s/apisix/c/apisix, I'm going to promote this link. I have two other questions:

1. When will it be indexed by Google?
2. If I have new messages in the same channel in the future, can I import the zip file directly? (Linen imports them and overrides existing content? or only import new messages?)

**Comment by sandrodesouza** [comment]
Hi @juzhiyuan

1. Your community is ready to be crawled by search bots. It also appears in our main sitemap. Google will eventually crawl your community, it will help to speed up this process by sharing your community url through the web.
2. You can upload a new zip file any time you want, it will override existing content, add new content if it exists, and keep old content even if the zip file doesn't have them anymore.
3. From the zip you send here I just unzip it, and it creates a folder called "apisix-channel", I opened that folder, selected all json files plus the folder "apisix", right click and the "compress" option. That is it. If you have problems, just write me back.

About pricing, the free edition still gets crawled by search bots, the business edition will improve that because you will have your domain, and it will be faster since it will only contain your community content to be crawled, in the free tier all free communities are sharing their content.

**Comment by cheeseblubber** [comment]
@juzhiyuan Also why don't you trigger a sync instead of a file upload? A sync will do everything you want. If you want other channels to be not indexed you can hide it in the settings page.

**Comment by juzhiyuan** [comment]
Thanks @sandrodesouza, it's clear now :)



> @juzhiyuan Also why don't you trigger a sync instead of a file upload? A sync will do everything you want. If you want other channels to be not indexed you can hide it in the settings page.

Hi @cheeseblubber, the reason is the workspace permission is limited under the foundation :) We don't have related permissions to sync contents.
