### ISSUE TITLE
browse communities page

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#789]
We need a page for users to browse their communities. It should be some sort of card view

Details on each card:
Community name with logo and color
Community description

Should do the simplest pagination and maybe based on creation time or the largest communities is the simplest. We should have Linen community pinned there

Here might be some inspiration:
https://dribbble.com/shots/18696944-MataJob-Job-Finder-Dashboard-View

Search for this view is out of scope of this story.

**Comment by emilos** [comment]
I've added a very basic communities page. Cards will look much better once communities upload the `logoSquareUrl` and add a description.
