### ISSUE TITLE
avatar image names are used verbatim causing 502 or worse

### ISSUE THREAD

**Issue by mdaniel** [Linen-dev/linen.dev#812]
> GET https://www.linen.dev/_next/image?url=https://linen-assets.s3.amazonaws.com/attachments/IMG_20190226_212747_219 540px.jpeg/IMG_20190226_212747_219 540px.jpeg&w=96&q=75

1. navigate to the Profile page
2. click Upload
3. use an image with a space in it (or worse, `foo"><script>alert(1);</script>.jpeg`)
4. watch the page reload
5. observe the 502 in every subsequent call to the avatar

**Comment by mdaniel** [comment]
Hmm, still getting the 502s even after using a more "reasonable" image name, so there's obviously something else going on here

**Comment by emilos** [comment]
Closing as this seemed to be a role error in our s3 bucket. Thanks!
