### ISSUE TITLE
avatar images are not allowed to be jpeg

### ISSUE THREAD

**Issue by mdaniel** [Linen-dev/linen.dev#813]
1. navigate to Profile
2. tap Upload
3. use a jpeg image
4. observe the 502s from https://www.linen.dev/_next/image?url=https%3A%2F%2Flinen-assets.s3.amazonaws.com%2Fattachments%2FIMG_20190226_212747_219_540px.jpeg%2FIMG_20190226_212747_219_540px.jpeg&w=96&q=75
5. instead use a .png
6. observe the 200 response and that the avatar changes

**Comment by emilos** [comment]
@mdaniel I'm having a hard time reproducing this one, I can upload jpg/jpeg/png correctly. Could you share the file you're trying to upload? Maybe that would help narrowing down the issue.

cc @sandrodesouza

**Comment by cheeseblubber** [comment]
@mdaniel We just fixed the issue. It was a role problem with our S3 bucket.
