### ISSUE TITLE
Merge duplicate channels when doing a Slack or Discord Sync

### ISSUE THREAD

**Issue by cheeseblubber** [Linen-dev/linen.dev#843]
Currently some communities will have a duplicate name and Linen will overwrite those. We should merge them instead

**Comment by sandrodesouza** [comment]
[feat(web): Merge duplicate channels when doing a Slack or Discord Sync](https://github.com/Linen-dev/linen.dev/commit/318e7454e3e045958fc31b4d9d499eb4274e4a66)
