### ISSUE TITLE
Does linen sync Slack DMs by any chance?

### ISSUE THREAD

**Issue by hezyin** [Linen-dev/linen.dev#889]
Hey guys, I just set up linen for my open-source community (https://www.linen.dev/s/apache-devlake) and I love it! I was wondering in addition to the public channels in Slack, does linen also sync Slack DMs by any chance? That would truly enable me to handle all community messages from one place, thanks in advance!

**Comment by emilos** [comment]
Hi @hezyin! Thanks a lot for the kind words. We currently do not, but we have DMs in our roadmap.
