### ISSUE TITLE
Discord not syncing #912

### ISSUE THREAD

**Issue by chris-y** [Linen-dev/linen.dev#912]
I signed up on linen.dev sometime ago and all was working fine until this year. I changed my Discord so it has a role required to see or post anything, since then Linen hasn't synced.
I have tried:
Adding the role to the Discord bot
Reconnecting to Discord (it appears the process has changed, so I've set up a new bot user with the instructions). When I put the bot key in it doesn't seem to keep it? I'm not sure if this is the issue.

Linen: https://www.linen.dev/d/ukdtt

**Comment by cheeseblubber** [comment]
Sorry about that Chris let us take a look. Our sync isn't instant and happens over a queue so might take some time but @sandrodesouza will have a look

**Comment by chris-y** [comment]
The delay is interesting, but I added the role ages ago and haven't seen anything come through. It's not that busy but I'm sure there have been messages since then.

**Comment by cheeseblubber** [comment]
Also sorry about the multiple github issue messages we're testing out a new sync with Github

**Comment by chris-y** [comment]
Excellent, thanks!
